/**
 * \file chaosmap.hpp
 * \brief Definitions for chaos maps, used in chaotic contexts to generate sequences of chaotic sequences.
 */

#ifndef _CHAOSMAP_HPP_
#define _CHAOSMAP_HPP_

#include "point.hpp"

#include <functional>

namespace Swarm
{
    /**
     * \brief Type definition for a chaos map function.
     * \tparam T The data type for the coordinates (default is float).
     * \tparam dim The dimensionality of the points (default is 2).
     * \see Point
     *
     * Instances of this type represents functions that take a Point and an integer (iteration count) as input and return a new Point.
     */
    template <typename T = float, int dim = 2>
    using MapFunction = std::function<Point<T, dim>(const Point<T, dim> &, int)>;

    /**
     * \brief Class representing a chaos map.
     * \tparam T The data type for the coordinates (default is float).
     * \tparam dim The dimensionality of the points (default is 2).
     * \see Point
     * \see MapFunction
     *
     * This class encapsulates a chaos map function along with methods to transform points between different coordinate domains.
     */
    template <typename T = float, int dim = 2>
    class ChaosMap
    {
    private:
        /**
         * \brief The mapper function used to generate new points.
         */
        MapFunction<T, dim> map;

        /**
         * \brief The minimum point defining the domain over which the map operates.
         */
        Point<T, dim> a_min;

        /**
         * \brief The maximum point defining the domain over which the map operates.
         */
        Point<T, dim> b_max;

        /**
         * \brief Maps a point from one domain to another.
         * \param point The point to be mapped.
         * \param first_range_start The start of the original domain.
         * \param first_range_end The end of the original domain.
         * \param min_range The start of the target domain.
         * \param max_range The end of the target domain.
         * \return A new point mapped to the target domain.
         * \see Point
         */
        inline Point<T, dim> mapBetweenDomains(const Point<T, dim> &point, const Point<T, dim> &first_range_start, const Point<T, dim> &first_range_end, const Point<T, dim> &min_range, const Point<T, dim> &max_range) const
        {
            // codice per trasformare le coordinate
            return (point - first_range_start) / (first_range_end - first_range_start) * (max_range - min_range) + min_range;
        };

        /**
         * \brief Generates a new point using the chaos map function.
         * \param point The input point.
         * \param iter The current iteration count.
         * \return A new point generated by the chaos map function.
         * \see MapFunction
         */
        inline Point<T, dim> generatePoint(const Point<T, dim> &point, int iter) const
        {
            // map evaluate point map(Point),per ogni dimensione genera per ogni coordinata
            return map(point, iter);
        };

    public:
        /**
         * \brief Constructs a ChaosMap with the given map function and domain boundaries.
         * \param lambda_fun The chaos map function.
         * \param min The minimum point defining the domain.
         * \param max The maximum point defining the domain.
         * \see MapFunction
         * \see Point
         */
        ChaosMap(const MapFunction<T, dim> &lambda_fun, const Point<T, dim> &min, const Point<T, dim> &max) : map(lambda_fun), a_min(min), b_max(max) {};

        /**
         * \brief Transforms a point from the Global domain to the Local domain.
         * \param point The point to be transformed.
         * \param min_range The minimum point defining the Global domain.
         * \param max_range The maximum point defining the Global domain.
         * \return A new point in the Local domain.
         * \see Point
         * \see mapBetweenDomains
         */
        inline Point<T, dim> toLocalDomain(const Point<T, dim> &point, const Point<T, dim> &min_range, const Point<T, dim> &max_range) const
        {
            return mapBetweenDomains(point, min_range, max_range, a_min, b_max);
        };

        /**
         * \brief Transforms a point from the Local domain to the Global domain.
         * \param point The point to be transformed.
         * \param min_range The minimum point defining the Global domain.
         * \param max_range The maximum point defining the Global domain.
         * \return A new point in the Global domain.
         * \see Point
         * \see mapBetweenDomains
         */
        inline Point<T, dim> toGlobalDomain(const Point<T, dim> &point, const Point<T, dim> &min_range, const Point<T, dim> &max_range) const
        {
            return mapBetweenDomains(point, a_min, b_max, min_range, max_range);
        };

        /**
         * \brief Generates a new point by applying the chaos map to a given point, transforming it between Global and Local domains.
         * \param point The input point in the Global domain.
         * \param min_global The minimum point defining the Global domain.
         * \param max_global The maximum point defining the Global domain.
         * \param iter The current iteration count.
         * \return A new point in the Global domain after applying the chaos map.
         * \see Point
         * \see toLocalDomain
         * \see generatePoint
         * \see toGlobalDomain
         */
        inline Point<T, dim> getPoint(const Point<T, dim> &point, const Point<T, dim> &min_global, const Point<T, dim> &max_global, int iter) const
        {
            Point<T, dim> new_point = toLocalDomain(point, min_global, max_global);
            new_point = generatePoint(new_point, iter);
            new_point = toGlobalDomain(new_point, min_global, max_global);

            return new_point;
        };
    };
};

#endif